services:
  postgres:
    image: postgres:16
    volumes:
      - ../keycloak/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    user: "501:20"  # this is for my mac

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    depends_on:
      - postgres
    environment:
      - KC_LOG_LEVEL=info,org.keycloak.authentication:debug
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_PASSWORD=password
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/localhost.key
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/localhost.crt
      - KC_HTTPS_CLIENT_AUTH=request
      - KEYCLOAK_HTTPS_CLIENT_AUTH=request
    ports:
      - 18080:8080
      - 18443:8443
    volumes:
      - ../keycloak/certs/keycloak.crt:/opt/keycloak/conf/localhost.crt
      - ../keycloak/certs/keycloak.key:/opt/keycloak/conf/localhost.key
      - ../keycloak/certs/myCA.jks:/opt/keycloak/conf/rootCA.jks
      - ../keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command: start-dev

  mongo:
    image: mongo:5.0.26
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - TZ=Australia/Sydney  # Set the timezone to Australian Eastern Time
    volumes:
      - ../mongodb/mongodb:/data/db
    user: "501:20"  # this is for my mac

  # https://localhost:18443/realms/jxhui/protocol/openid-connect/auth?client_id=root&response_type=token&scope=openid&redirect_uri=http://localhost:4200


  # https://localhost:18443/realms/jxhui/account/