version: "3.8"
services:
  mongo:
    image: mongo:5.0.26
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - TZ=Australia/Sydney  # Set the timezone to Australian Eastern Time
    volumes:
      - ./mongodb:/data/db
    user: "501:20"  # this is for my mac